export const backendToFrontendPathMap: Record<string, string> = {
  '/dashboard': '/dashboard',
  '/material/list': '/material',
  '/material-management': '/material',
  '/material/supplier': '/material/supplier',
  '/material-management/supplier': '/material/supplier',
  '/material/customer': '/material/customer',
  '/material-management/customer': '/material/customer',
  '/material/product': '/material/product',
  '/material-management/product': '/material/product',
  '/stock/product': '/stock/product',
  '/inventory-management/product-stock': '/stock/product',
  '/stock/material': '/stock/material',
  '/inventory-management/material-stock': '/stock/material',
  '/basic/alarm': '/log/alarm',
  '/management/log/alarm': '/log/alarm',
  '/basic/warehouse': '/stock/warehouse-location',
  '/base/wms': '/stock/warehouse-location',
  '/inventory-management/warehouse-location': '/stock/warehouse-location',
  '/work-order/list': '/order/order',
  '/work-order-management/list': '/order/order',
  '/work-order/craft': '/order/craft',
  '/work-order-management/craft': '/order/craft',
  '/craft/craft': '/order/craft',
  '/work-order/recipe': '/order/recipe',
  '/work-order-management/recipe': '/order/recipe',
  '/base/recipe': '/order/recipe',
  '/equipment/station': '/equipment/station',
  '/equipment-management/station': '/equipment/station',
  '/equipment/list': '/equipment/list',
  '/equipment-management/list': '/equipment/list',
  '/equipment/sensor': '/equipment/sensor',
  '/equipment-management/sensor': '/equipment/sensor',
  '/equipment/repair': '/equipment/repair-order',
  '/equipment-management/repair-order': '/equipment/repair-order',
  '/ai/chat': '/ai/chat',
  '/ai/assistant/chat': '/ai/chat',
  '/ai/production-report': '/ai/production-report',
  '/ai/assistant/production-report': '/ai/production-report',
  '/ai/daily-report': '/ai/device-report',
  '/ai/assistant/device-report': '/ai/device-report',
  '/ai/trace': '/ai/traceability',
  '/ai/assistant/traceability': '/ai/traceability',
  '/ai/quality': '/ai/batch-quality',
  '/ai/assistant/batch-quality': '/ai/batch-quality',
  '/ai/knowledge': '/basic/knowledge',
  '/management/basic/knowledge': '/basic/knowledge',
  '/ai/rules': '/basic/rules',
  '/management/basic/rules': '/basic/rules',
  '/ai/decision-log': '/log/decisions',
  '/management/log/decisions': '/log/decisions',
  '/system/user': '/system/user',
  '/system/role': '/system/role',
  '/system/menu': '/system/menu',
  '/system/dict': '/system/dict',
  '/system/dict-type': '/system/dict',
}

export const normalizeMenuPath = (path?: string | null) => {
  if (!path || typeof path !== 'string') return ''
  return backendToFrontendPathMap[path] || path
}
